//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public Connection()
        {
            this.Game = new HashSet<Play>();
        }
    
        public int Id { get; set; }
        public int CallerUserId { get; set; }
        public Nullable<int> CalledUserId { get; set; }
        public Nullable<int> CurrentPlayId { get; set; }
    
        public virtual User CallerUser { get; set; }
        public virtual ICollection<Play> Game { get; set; }
    }
}
