//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public Play()
        {
            this.PlayMove = new HashSet<PlayMove>();
        }
    
        public int Id { get; set; }
        public int ConnectionId { get; set; }
    
        public virtual Connection Connection { get; set; }
        public virtual ICollection<PlayMove> PlayMove { get; set; }
    }
}
