//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Move = new HashSet<Move>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CurrentPlayId { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Move> Move { get; set; }
    }
}
